### ISSUE TITLE
Display of non-identifier property names

### ISSUE THREAD

**Issue by tmedwards** [cyrusfirheir/sc-debugger#1]
Property names that are not valid identifiers are currently displayed via the dot notation, when they really should be using the square bracket notation.  That should probably be checked for and handled if you want the display to mimic actual usage in TwineScript/JavaScript.

For example, the following sets up an object whose property names are not valid identifiers—not an exhaustive example—and would thus require the use of the square bracket notation in actual usage:

```
<<set $foo to {
	'a property'   : 1,
	'a "property"' : 2,
	"a 'property'" : 3,
	"a #property"  : 4
}>>
```

Currently display in dot notation:

```
$foo.a property
$foo.a "property"
$foo.a 'property'
$foo.a #property
```

When square bracket notation would be more appropriate:

```
$foo.["a property"]
$foo.["a \"property\""]
$foo.["a 'property'"]
$foo.["a #property"]
```

**Comment by cyrusfirheir** [comment]
Do those invalid property names cause problems like setting the values to some other (new) variable than the original? Lodash's _.set() does work pretty well under the hood, and npm Flat is taking care of property names
while flattening the variables object. (Sorry I'm on mobile for the next 20 hrs or so; I can test things on it, but will take a while.)

Currently, what the debugger window displays is just a a regex replaced version of what I'm using as their <div> IDs. Purely superficial. I should be able to change it to display bracket notation properly too.

One problem that I did expect myself was when someone uses a number as an object property name. That would convert that property into an array element. And if the object had other properties which aren't named with
numbers, it can throw an error. I think it's not a big thing to fix, given Lodash's _.setWith() function, so I'll get around to it tomorrow.

Do let me know of any other things you find! And thanks for checking it out!

**Comment by cyrusfirheir** [comment]
Just tested, and this does breaks things. I have an idea as to how to fix it, just need to run some more tests. Prolly will have a patch up tomorrow.

**Comment by cyrusfirheir** [comment]
Just pushed v0.1.2, fixing this and another problem where similarly named variables could set the same value.
