### ISSUE TITLE
good theme and styling

### ISSUE THREAD

**Issue by arohman84** [cyrusfirheir/sc-debugger#3]
Hello, can you please tell me what game or the url for this ? i love the theme and styling
![68747470733a2f2f696d6775722e636f6d2f51427a755669552e706e67](https://user-images.githubusercontent.com/2444037/97833002-d7a73180-1d06-11eb-85f9-e46b15b63d3d.png)
and this
![68747470733a2f2f696d6775722e636f6d2f5854374b4e41612e706e67](https://user-images.githubusercontent.com/2444037/97833024-e55cb700-1d06-11eb-9382-25476f295882.png)

and if still in development, can i ask the source please? no logic is fine, just want the theme and styling. thx before

**Comment by cyrusfirheir** [comment]
These screenshots are from old abandoned projects of mine. Sorry, I don't really have the files for them anymore.

Conceptually though, the first one uses the [field-set element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset), and the second one uses [clip paths](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path). That's all there is to it.

Also, I don't know if this warranted a GH issue, really... If you want more help with this stuff, you might want to join the [Twine Games Discord server](https://discord.gg/n5dJvPp). It'll be easier to explain things there.

Closing.
